INSERT INTO `db_sb_cloud`.`products` (nombre, precio, create_at) VALUES ('PS4', 900, NOW());
INSERT INTO `db_sb_cloud`.`products` (nombre, precio, create_at) VALUES ('Xbox', 930, NOW());
INSERT INTO `db_sb_cloud`.`products` (nombre, precio, create_at) VALUES ('Note', 1000, NOW());
INSERT INTO `db_sb_cloud`.`products` (nombre, precio, create_at) VALUES ('TV', 1200, NOW());
INSERT INTO `db_sb_cloud`.`products` (nombre, precio, create_at) VALUES ('Alexa', 100, NOW());
INSERT INTO `db_sb_cloud`.`products` (nombre, precio, create_at) VALUES ('Iphone', 1300, NOW());
INSERT INTO `db_sb_cloud`.`products` (nombre, precio, create_at) VALUES ('Rasperry', 30, NOW());
INSERT INTO `db_sb_cloud`.`products` (nombre, precio, create_at) VALUES ('PC', 3000, NOW());
INSERT INTO `db_sb_cloud`.`products` (nombre, precio, create_at) VALUES ('Bose', 3100, NOW());